# Form implementation generated from reading ui file 'f:\dudu\python\电子书阅读器\ui\main.ui'
#
# Created by: PySide6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from ui import textEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 340)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.text = textEdit(parent=self.centralwidget)
        self.text.setReadOnly(True)
        self.text.setObjectName("text")
        self.gridLayout.addWidget(self.text, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 436, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(parent=self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(parent=self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(parent=self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.massager = QtWidgets.QStatusBar(parent=MainWindow)
        self.massager.setObjectName("massager")
        MainWindow.setStatusBar(self.massager)
        self.dockWidget = QtWidgets.QDockWidget(parent=MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.showNovelList = QtWidgets.QTreeWidget(parent=self.dockWidgetContents)
        self.showNovelList.setObjectName("showNovelList")
        self.gridLayout_2.addWidget(self.showNovelList, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.open = QtGui.QAction(parent=MainWindow)
        self.open.setObjectName("open")
        self.enterRe = QtGui.QAction(parent=MainWindow)
        self.enterRe.setObjectName("enterRe")
        self.openList = QtGui.QAction(parent=MainWindow)
        self.openList.setObjectName("openList")
        self.setFont = QtGui.QAction(parent=MainWindow)
        self.setFont.setObjectName("setFont")
        self.startDownload = QtGui.QAction(parent=MainWindow)
        self.startDownload.setObjectName("startDownload")
        self.menu.addAction(self.open)
        self.menu_2.addAction(self.enterRe)
        self.menu_2.addAction(self.openList)
        self.menu_3.addAction(self.setFont)
        self.menu_3.addAction(self.startDownload)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "目录"))
        self.menu_3.setTitle(_translate("MainWindow", "设置"))
        self.showNovelList.headerItem().setText(0, _translate("MainWindow", "目录"))
        self.open.setText(_translate("MainWindow", "打开"))
        self.enterRe.setText(_translate("MainWindow", "输入正则表达式"))
        self.openList.setText(_translate("MainWindow", "打开目录"))
        self.setFont.setText(_translate("MainWindow", "设置字体"))
        self.startDownload.setText(_translate("MainWindow", "启动电子书下载器"))
