# Form implementation generated from reading ui file 'd:\Admin\Documents\dudu\python\下载器\ui\main.ui'
#
# Created by: PySide6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 304)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.bitSize = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.bitSize.setPrefix("")
        self.bitSize.setMinimum(1)
        self.bitSize.setMaximum(10240)
        self.bitSize.setSingleStep(1)
        self.bitSize.setStepType(QtWidgets.QAbstractSpinBox.StepType.DefaultStepType)
        self.bitSize.setProperty("value", 1)
        self.bitSize.setDisplayIntegerBase(10)
        self.bitSize.setObjectName("bitSize")
        self.gridLayout.addWidget(self.bitSize, 1, 2, 1, 1)
        self.url = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.url.setObjectName("url")
        self.gridLayout.addWidget(self.url, 0, 0, 1, 4)
        self.info = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.info.setObjectName("info")
        self.gridLayout.addWidget(self.info, 2, 0, 1, 4)
        self.savePath = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.savePath.setReadOnly(True)
        self.savePath.setObjectName("savePath")
        self.gridLayout.addWidget(self.savePath, 1, 0, 1, 1)
        self.start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start.setObjectName("start")
        self.gridLayout.addWidget(self.start, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bitSize.setSuffix(_translate("MainWindow", "M"))
        self.url.setPlaceholderText(_translate("MainWindow", "输入下载链接"))
        self.savePath.setPlaceholderText(_translate("MainWindow", "保存路径(开始下载后自动生成)"))
        self.start.setText(_translate("MainWindow", "开始下载"))
        self.label.setText(_translate("MainWindow", "块大小"))
