# Form implementation generated from reading ui file 'D:/Users/Admin/Documents/Git/python/游戏/问答/ui/Ui.ui'
#
# Created by: PySide6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 227)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Open = QtWidgets.QPushButton(self.centralwidget)
        self.Open.setObjectName("Open")
        self.gridLayout_2.addWidget(self.Open, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.B = QtWidgets.QPushButton(self.centralwidget)
        self.B.setObjectName("B")
        self.gridLayout.addWidget(self.B, 2, 1, 1, 1)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setObjectName("start")
        self.gridLayout.addWidget(self.start, 1, 1, 1, 1)
        self.show2 = QtWidgets.QLabel(self.centralwidget)
        self.show2.setObjectName("show2")
        self.gridLayout.addWidget(self.show2, 1, 2, 1, 1)
        self.C = QtWidgets.QPushButton(self.centralwidget)
        self.C.setObjectName("C")
        self.gridLayout.addWidget(self.C, 2, 2, 1, 1)
        self.A = QtWidgets.QPushButton(self.centralwidget)
        self.A.setObjectName("A")
        self.gridLayout.addWidget(self.A, 2, 0, 1, 1)
        self.show1 = QtWidgets.QLabel(self.centralwidget)
        self.show1.setObjectName("show1")
        self.gridLayout.addWidget(self.show1, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Show = QtWidgets.QLabel(self.centralwidget)
        self.Show.setObjectName("Show")
        self.verticalLayout.addWidget(self.Show)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Open.setText(_translate("MainWindow", "打开题目文件"))
        self.B.setText(_translate("MainWindow", "B"))
        self.start.setText(_translate("MainWindow", "开始"))
        self.show2.setText(_translate("MainWindow", "次数：0"))
        self.C.setText(_translate("MainWindow", "C"))
        self.A.setText(_translate("MainWindow", "A"))
        self.show1.setText(_translate("MainWindow", "分数：0"))
        self.Show.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">None</p><p align=\"center\">None</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
