# Form implementation generated from reading ui file 'D:/Users/Admin/Documents/Git/python/游戏/打地鼠/ui/Ui.ui'
#
# Created by: PySide6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 255)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Show = QtWidgets.QLabel(self.centralwidget)
        self.Show.setObjectName("Show")
        self.verticalLayout.addWidget(self.Show)
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setObjectName("Start")
        self.verticalLayout.addWidget(self.Start)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.a1 = QtWidgets.QLabel(self.centralwidget)
        self.a1.setObjectName("a1")
        self.gridLayout.addWidget(self.a1, 0, 0, 1, 1)
        self.a2 = QtWidgets.QLabel(self.centralwidget)
        self.a2.setObjectName("a2")
        self.gridLayout.addWidget(self.a2, 0, 1, 1, 1)
        self.a3 = QtWidgets.QLabel(self.centralwidget)
        self.a3.setObjectName("a3")
        self.gridLayout.addWidget(self.a3, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setObjectName("b1")
        self.horizontalLayout.addWidget(self.b1)
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setObjectName("b2")
        self.horizontalLayout.addWidget(self.b2)
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3.setObjectName("b3")
        self.horizontalLayout.addWidget(self.b3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Show.setText(_translate("MainWindow", " "))
        self.Start.setText(_translate("MainWindow", "开始"))
        self.a1.setText(_translate("MainWindow", " "))
        self.a2.setText(_translate("MainWindow", " "))
        self.a3.setText(_translate("MainWindow", " "))
        self.b1.setText(_translate("MainWindow", "1"))
        self.b2.setText(_translate("MainWindow", "2"))
        self.b3.setText(_translate("MainWindow", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
